-- Create table for application settings (key-value store)
create table if not exists public.app_settings (
    key text primary key,
    value text, -- can store JSON or string
    updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- RLS for settings
alter table public.app_settings enable row level security;

create policy "Settings viewable by authenticated users"
    on public.app_settings for select
    to authenticated
    using (true);

create policy "Settings updatable by authenticated users" 
    on public.app_settings for insert 
    to authenticated 
    with check (true);

create policy "Settings updatable by authenticated users update" 
    on public.app_settings for update
    to authenticated 
    using (true);

-- Create table for announcements
create table if not exists public.announcements (
    id bigint generated by default as identity primary key,
    title text not null,
    content text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    date date default CURRENT_DATE,
    status text default 'Active', -- Active, Inactive
    author_id uuid references public.profiles(id)
);

-- RLS for announcements
alter table public.announcements enable row level security;

create policy "Announcements viewable by everyone"
    on public.announcements for select
    to authenticated
    using (true);

create policy "Announcements manage by authenticated"
    on public.announcements for all
    to authenticated
    using (true);
