-- ============================================
-- COMPLETE DATABASE RESET - CORRECTED VERSION
-- ============================================
-- WARNING: This will DELETE ALL DATA in your application tables!
-- This does NOT delete auth.users (your login accounts remain)
-- Run this in Supabase SQL Editor
-- ============================================

-- Step 1: Drop all existing tables (in correct order to avoid foreign key issues)
DROP TABLE IF EXISTS public.attendance CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;
DROP TABLE IF EXISTS public.announcements CASCADE;
DROP TABLE IF EXISTS public.ministries CASCADE;
DROP TABLE IF EXISTS public.clusters CASCADE;
DROP TABLE IF EXISTS public.roles CASCADE;
DROP TABLE IF EXISTS public.app_settings CASCADE;

-- Step 2: Create the profiles table
CREATE TABLE public.profiles (
    id uuid REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    full_name text,
    email text,
    role text,
    cluster text,
    ministry text,
    phone text,
    address text,
    birthday date,
    gender text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Step 3: Create the roles table (WITH ID for signup)
CREATE TABLE public.roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    description text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Step 4: Create the clusters table (NO ID - name is primary key)
CREATE TABLE public.clusters (
    name text PRIMARY KEY,
    leader text,
    description text,
    schedule text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Step 5: Create the ministries table (NO ID - name is primary key)
CREATE TABLE public.ministries (
    name text PRIMARY KEY,
    leader text,
    description text,
    schedule text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Step 6: Create the announcements table
CREATE TABLE public.announcements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    date text NOT NULL,
    status text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Step 7: Create the attendance table
CREATE TABLE public.attendance (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    date date NOT NULL,
    status text NOT NULL,
    cluster text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Step 8: Create the app_settings table
CREATE TABLE public.app_settings (
    key text PRIMARY KEY,
    value text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ============================================
-- ENABLE ROW LEVEL SECURITY (RLS)
-- ============================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clusters ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ministries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;

-- ============================================
-- CREATE RLS POLICIES
-- ============================================

-- Profiles policies
CREATE POLICY "Users can view all profiles"
    ON public.profiles FOR SELECT
    TO authenticated
    USING (true);

CREATE POLICY "Users can update own profile"
    ON public.profiles FOR UPDATE
    TO authenticated
    USING (auth.uid() = id);

CREATE POLICY "Users can insert own profile"
    ON public.profiles FOR INSERT
    TO authenticated
    WITH CHECK (auth.uid() = id);

-- Roles policies
CREATE POLICY "Roles viewable by authenticated users"
    ON public.roles FOR SELECT
    TO authenticated
    USING (true);

CREATE POLICY "Roles manageable by authenticated users"
    ON public.roles FOR ALL
    TO authenticated
    USING (true);

-- Clusters policies
CREATE POLICY "Clusters viewable by authenticated users"
    ON public.clusters FOR SELECT
    TO authenticated
    USING (true);

CREATE POLICY "Clusters manageable by authenticated users"
    ON public.clusters FOR ALL
    TO authenticated
    USING (true);

-- Ministries policies
CREATE POLICY "Ministries viewable by authenticated users"
    ON public.ministries FOR SELECT
    TO authenticated
    USING (true);

CREATE POLICY "Ministries manageable by authenticated users"
    ON public.ministries FOR ALL
    TO authenticated
    USING (true);

-- Announcements policies
CREATE POLICY "Announcements viewable by authenticated users"
    ON public.announcements FOR SELECT
    TO authenticated
    USING (true);

CREATE POLICY "Announcements manageable by authenticated users"
    ON public.announcements FOR ALL
    TO authenticated
    USING (true);

-- Attendance policies
CREATE POLICY "Attendance viewable by authenticated users"
    ON public.attendance FOR SELECT
    TO authenticated
    USING (true);

CREATE POLICY "Attendance manageable by authenticated users"
    ON public.attendance FOR ALL
    TO authenticated
    USING (true);

-- App Settings policies
CREATE POLICY "App settings viewable by authenticated users"
    ON public.app_settings FOR SELECT
    TO authenticated
    USING (true);

CREATE POLICY "App settings manageable by authenticated users"
    ON public.app_settings FOR ALL
    TO authenticated
    USING (true);

-- ============================================
-- INSERT DEFAULT DATA
-- ============================================

-- Insert default roles (WITH IDs)
INSERT INTO public.roles (name, description) VALUES
    ('Member', 'Regular church member with basic access'),
    ('Logistics', 'Handles logistics and operational tasks'),
    ('Volunteer', 'Assists with events and activities'),
    ('Ministry Leader', 'Leads and manages a ministry'),
    ('Administrator', 'Full administrative access to the system');

-- Insert default app settings
INSERT INTO public.app_settings (key, value) VALUES
    ('general', '{"churchName":"LampKonek Church","address":"123 Main Street, City, Country","phone":"+63 912 345 6789","email":"info@lampkonek.church"}'),
    ('reservations', '{"expirationDays":7,"terms":"1. Reservation Approval\\nAll reservations are subject to approval by the church administration.\\n\\n2. Reservation Period\\nReservations expire after 7 days if not approved or used.\\n\\n3. Cancellation Policy\\nCancellations must be made at least 48 hours before the scheduled event."}');

-- ============================================
-- CREATE FUNCTION TO AUTO-CREATE PROFILE
-- ============================================

-- Drop existing function if it exists
DROP FUNCTION IF EXISTS public.handle_new_user() CASCADE;

-- Create function to automatically create a profile when a new user signs up
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, full_name, email, role)
    VALUES (
        NEW.id,
        NEW.raw_user_meta_data->>'full_name',
        NEW.email,
        NEW.raw_user_meta_data->>'role'
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Drop existing trigger if it exists
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

-- Create trigger to call the function when a new user is created
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_new_user();

-- ============================================
-- VERIFICATION
-- ============================================

-- Check that all tables were created
SELECT 
    table_name,
    (SELECT COUNT(*) FROM information_schema.columns WHERE table_name = t.table_name AND table_schema = 'public') as column_count
FROM information_schema.tables t
WHERE table_schema = 'public'
    AND table_type = 'BASE TABLE'
ORDER BY table_name;

-- Show roles (with IDs)
SELECT id, name, description FROM public.roles ORDER BY id;

-- Show app settings
SELECT key FROM public.app_settings ORDER BY key;

-- ============================================
-- SUCCESS MESSAGE
-- ============================================
-- If you see the tables and data above, your database has been reset successfully!
-- 
-- SCHEMA SUMMARY:
-- ✅ Roles table: HAS ID (for signup dropdown)
-- ✅ Clusters table: NO ID (name is primary key)
-- ✅ Ministries table: NO ID (name is primary key)
-- ✅ Profiles, Announcements, Attendance: Have IDs
-- 
-- NEXT STEPS:
-- 1. Sign up for an account
-- 2. Run migrations/set_administrator.sql to make yourself admin
-- 3. Start using the application!
-- ============================================
