-- Create clusters table
CREATE TABLE IF NOT EXISTS public.clusters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    leader TEXT,
    description TEXT,
    schedule TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.clusters ENABLE ROW LEVEL SECURITY;

-- Allow public read access to clusters
CREATE POLICY "Public clusters are viewable by everyone" ON public.clusters
    FOR SELECT USING (true);

-- Allow authenticated users (admins) to insert/update/delete clusters
CREATE POLICY "Admins can insert clusters" ON public.clusters
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Admins can update clusters" ON public.clusters
    FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Admins can delete clusters" ON public.clusters
    FOR DELETE USING (auth.role() = 'authenticated');

-- Insert default clusters if table is empty
INSERT INTO public.clusters (name, leader, description)
SELECT 'Cluster A', 'Leader A', 'Default Cluster A'
WHERE NOT EXISTS (SELECT 1 FROM public.clusters WHERE name = 'Cluster A');

INSERT INTO public.clusters (name, leader, description)
SELECT 'Cluster B', 'Leader B', 'Default Cluster B'
WHERE NOT EXISTS (SELECT 1 FROM public.clusters WHERE name = 'Cluster B');

INSERT INTO public.clusters (name, leader, description)
SELECT 'Cluster C', 'Leader C', 'Default Cluster C'
WHERE NOT EXISTS (SELECT 1 FROM public.clusters WHERE name = 'Cluster C');

INSERT INTO public.clusters (name, leader, description)
SELECT 'Cluster D', 'Leader D', 'Default Cluster D'
WHERE NOT EXISTS (SELECT 1 FROM public.clusters WHERE name = 'Cluster D');
