-- Create ministries table
CREATE TABLE IF NOT EXISTS public.ministries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    leader TEXT,
    description TEXT,
    schedule TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.ministries ENABLE ROW LEVEL SECURITY;

-- Allow public read access to ministries
CREATE POLICY "Public ministries are viewable by everyone" ON public.ministries
    FOR SELECT USING (true);

-- Allow authenticated users (admins) to insert/update/delete ministries
CREATE POLICY "Admins can insert ministries" ON public.ministries
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Admins can update ministries" ON public.ministries
    FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Admins can delete ministries" ON public.ministries
    FOR DELETE USING (auth.role() = 'authenticated');

-- Insert default ministries if table is empty
INSERT INTO public.ministries (name, leader, description)
SELECT 'Worship Team', 'Leader A', 'Music and Arts Ministry'
WHERE NOT EXISTS (SELECT 1 FROM public.ministries WHERE name = 'Worship Team');

INSERT INTO public.ministries (name, leader, description)
SELECT 'Kids Ministry', 'Leader B', 'Childrens Church'
WHERE NOT EXISTS (SELECT 1 FROM public.ministries WHERE name = 'Kids Ministry');

INSERT INTO public.ministries (name, leader, description)
SELECT 'Ushering', 'Leader C', 'Welcoming Team'
WHERE NOT EXISTS (SELECT 1 FROM public.ministries WHERE name = 'Ushering');

INSERT INTO public.ministries (name, leader, description)
SELECT 'Multimedia', 'Leader D', 'Tech and Media'
WHERE NOT EXISTS (SELECT 1 FROM public.ministries WHERE name = 'Multimedia');
