-- Run this in your Supabase SQL Editor to create the attendance table

-- 1. Create the attendance table
create table if not exists public.attendance (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    member_id uuid references public.profiles(id) not null,
    date date not null, -- stored as YYYY-MM-DD
    event text not null,
    status text not null, -- 'Present', 'Absent', 'Late', 'Excused'
    remarks text,

    -- Unique constraint to prevent duplicate attendance records for the same person/event/day
    constraint unique_attendance_record unique (member_id, date, event)
);

-- 2. Enable Row Level Security (RLS)
alter table public.attendance enable row level security;

-- 3. Create Policies

-- Allow authenticated users to view all attendance records
create policy "Attendance is viewable by authenticated users"
    on public.attendance for select
    to authenticated
    using (true);

-- Allow authenticated users to insert attendance records
create policy "Authenticated users can insert attendance"
    on public.attendance for insert
    to authenticated
    with check (true);

-- Allow authenticated users to update attendance records
create policy "Authenticated users can update attendance"
    on public.attendance for update
    to authenticated
    using (true);

-- Allow authenticated users to delete attendance records
create policy "Authenticated users can delete attendance"
    on public.attendance for delete
    to authenticated
    using (true);
