-- Create roles table
create table if not exists public.roles (
    id bigint generated by default as identity primary key,
    name text not null unique,
    description text,
    permissions text[], -- Array of strings
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS
alter table public.roles enable row level security;

create policy "Roles viewable by authenticated users"
    on public.roles for select
    to authenticated
    using (true);

create policy "Roles manage by authenticated users"
    on public.roles for all
    to authenticated
    using (true);

-- Insert default roles if they don't exist
insert into public.roles (name, description, permissions)
values 
    ('Admin', 'Full access to all system features', ARRAY['all']),
    ('Ministry Leader', 'Manage ministry members and events', ARRAY['manage_members', 'manage_events']),
    ('Volunteer', 'Assist with events and attendance', ARRAY['view_events', 'take_attendance']),
    ('Member', 'Regular member access', ARRAY['view_profile'])
on conflict (name) do nothing;
