-- Migration: Reset user roles and populate roles table
-- This script will:
-- 1. Set all user roles to NULL (reset them)
-- 2. Create the roles table if it doesn't exist
-- 3. Populate it with the standard roles from the signup form

-- Step 1: Reset all user roles to NULL
UPDATE public.profiles SET role = NULL;

-- Step 2: Create roles table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    description text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Step 3: Enable RLS on roles table
ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;

-- Step 4: Create policies for roles table
DROP POLICY IF EXISTS "Roles viewable by authenticated users" ON public.roles;
CREATE POLICY "Roles viewable by authenticated users"
    ON public.roles FOR SELECT
    TO authenticated
    USING (true);

DROP POLICY IF EXISTS "Roles manageable by authenticated users" ON public.roles;
CREATE POLICY "Roles manageable by authenticated users"
    ON public.roles FOR ALL
    TO authenticated
    USING (true);

-- Step 5: Insert the standard roles (matching the signup form)
INSERT INTO public.roles (name, description)
VALUES 
    ('Member', 'Regular church member with basic access'),
    ('Logistics', 'Handles logistics and operational tasks'),
    ('Volunteer', 'Assists with events and activities'),
    ('Ministry Leader', 'Leads and manages a ministry'),
    ('Administrator', 'Full administrative access to the system')
ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description;

-- Step 6: Verify the migration
SELECT * FROM public.roles ORDER BY name;
